//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webseal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Webseal.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lead has been allocated successfully.
        /// </summary>
        internal static string AllocationSuccess {
            get {
                return ResourceManager.GetString("AllocationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a lead business unit..
        /// </summary>
        internal static string BusUnit {
            get {
                return ResourceManager.GetString("BusUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ByPassWebSeal {
            get {
                return ResourceManager.GetString("ByPassWebSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Number is required.
        /// </summary>
        internal static string CellNumber {
            get {
                return ResourceManager.GetString("CellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a contact number for Client .i.e. Home,Work or Cell..
        /// </summary>
        internal static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth is required.
        /// </summary>
        internal static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B170760.
        /// </summary>
        internal static string domainUser {
            get {
                return ResourceManager.GetString("domainUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid email address - no email will be sent.
        /// </summary>
        internal static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leads-noreply@sanlam.co.za.
        /// </summary>
        internal static string FromMail {
            get {
                return ResourceManager.GetString("FromMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leadsgeneration@sanlam.co.za.
        /// </summary>
        internal static string FromMailLCD {
            get {
                return ResourceManager.GetString("FromMailLCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Telephone is required.
        /// </summary>
        internal static string HomeTelephone {
            get {
                return ResourceManager.GetString("HomeTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter client&apos;s ID number or Date of Birth.
        /// </summary>
        internal static string IdDOB {
            get {
                return ResourceManager.GetString("IdDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Number is required.
        /// </summary>
        internal static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediary Code is required.
        /// </summary>
        internal static string IntermediaryCode {
            get {
                return ResourceManager.GetString("IntermediaryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Email Address is not a valid email address.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InValid Number.
        /// </summary>
        internal static string InvalidIDNumber {
            get {
                return ResourceManager.GetString("InvalidIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is invalid.
        /// </summary>
        internal static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one recipient..
        /// </summary>
        internal static string IsEmailChecked {
            get {
                return ResourceManager.GetString("IsEmailChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the email address..
        /// </summary>
        internal static string IsNotEmail {
            get {
                return ResourceManager.GetString("IsNotEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a Region!.
        /// </summary>
        internal static string IsRegion {
            get {
                return ResourceManager.GetString("IsRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to technical problems the Leads System is not available at present. Please try again later..
        /// </summary>
        internal static string IsTechnicalIssue {
            get {
                return ResourceManager.GetString("IsTechnicalIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no access / proxy to the Leads system..
        /// </summary>
        internal static string LeadNoAccess {
            get {
                return ResourceManager.GetString("LeadNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a lead type.
        /// </summary>
        internal static string LeadType {
            get {
                return ResourceManager.GetString("LeadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comments field has more than 500 characters in it.
        /// </summary>
        internal static string MaxCommentLength {
            get {
                return ResourceManager.GetString("MaxCommentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Number is required.
        /// </summary>
        internal static string MemberNumber {
            get {
                return ResourceManager.GetString("MemberNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter client&apos;s name and surname.
        /// </summary>
        internal static string NameSurname {
            get {
                return ResourceManager.GetString("NameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Proxy Data Found..
        /// </summary>
        internal static string NoProxyData {
            get {
                return ResourceManager.GetString("NoProxyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is required.
        /// </summary>
        internal static string OverrideComments {
            get {
                return ResourceManager.GetString("OverrideComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply an Override Intermediary Code!.
        /// </summary>
        internal static string OverrideIntermediaryCode {
            get {
                return ResourceManager.GetString("OverrideIntermediaryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Intermediary Codes must be 8 long!.
        /// </summary>
        internal static string OverrideIntermediaryCodeLength {
            get {
                return ResourceManager.GetString("OverrideIntermediaryCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date in the past!.
        /// </summary>
        internal static string PastFromDateProxy {
            get {
                return ResourceManager.GetString("PastFromDateProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User cannot create a proxy for Himself/herself!.
        /// </summary>
        internal static string ProxyAndRACFid {
            get {
                return ResourceManager.GetString("ProxyAndRACFid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a From date!.
        /// </summary>
        internal static string ProxyFromDate {
            get {
                return ResourceManager.GetString("ProxyFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a Proxy ID!.
        /// </summary>
        internal static string ProxyId {
            get {
                return ResourceManager.GetString("ProxyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a To date!.
        /// </summary>
        internal static string ProxyToDate {
            get {
                return ResourceManager.GetString("ProxyToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Id must be in the format 1xAlfaNumeric, 6xNumeric and a space in the last position!.
        /// </summary>
        internal static string RACFFormat {
            get {
                return ResourceManager.GetString("RACFFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a User Id!.
        /// </summary>
        internal static string RACFId {
            get {
                return ResourceManager.GetString("RACFId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Id must be 8 long!.
        /// </summary>
        internal static string RACFLength {
            get {
                return ResourceManager.GetString("RACFLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create a prospect lead you must enter a &apos;region code&apos; or &apos;intermediary code&apos;..
        /// </summary>
        internal static string RegionValidate {
            get {
                return ResourceManager.GetString("RegionValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Lead Type is required.
        /// </summary>
        internal static string RejectLead {
            get {
                return ResourceManager.GetString("RejectLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a reason for rejection..
        /// </summary>
        internal static string RejectReason {
            get {
                return ResourceManager.GetString("RejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string SanportProxyStartChar {
            get {
                return ResourceManager.GetString("SanportProxyStartChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select proxy to login..
        /// </summary>
        internal static string SelectProxyMsg {
            get {
                return ResourceManager.GetString("SelectProxyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail.sanlam.co.za.
        /// </summary>
        internal static string SMTPSERVER {
            get {
                return ResourceManager.GetString("SMTPSERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a lead source..
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date &gt; a year in the future!.
        /// </summary>
        internal static string ToDateValidateProxy {
            get {
                return ResourceManager.GetString("ToDateValidateProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User.
        /// </summary>
        internal static string UnauthorisedUser {
            get {
                return ResourceManager.GetString("UnauthorisedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sanport-dev.sanlam.co.za/sanleads/?parm=YvHPYxFlq%2bZq%2bnk9ufFNQqYvAp1JHYIr0t5ZcPKuqbBXfHtEyJCfwd5mNgEWMZzB8N3u4YH%2bH5X7Ur7zfCrefZ%2fVvkbl5tu4kXhsohkmkck%3d&amp;lang=E.
        /// </summary>
        internal static string urlParam {
            get {
                return ResourceManager.GetString("urlParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:50735/.
        /// </summary>
        internal static string WebApiBaseUrl {
            get {
                return ResourceManager.GetString("WebApiBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sanleads-dev.sanlam.co.za/salesleadsapi/.
        /// </summary>
        internal static string WebApiBaseUrlLive {
            get {
                return ResourceManager.GetString("WebApiBaseUrlLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S@LesSVC@cc0unT.
        /// </summary>
        internal static string WebAPIPassword {
            get {
                return ResourceManager.GetString("WebAPIPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUD\SvcNprdSpfSanLeadAcc.
        /// </summary>
        internal static string WebAPIUser {
            get {
                return ResourceManager.GetString("WebAPIUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithParams.
        /// </summary>
        internal static string WithParams {
            get {
                return ResourceManager.GetString("WithParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Telephone is required.
        /// </summary>
        internal static string WorkTelephone {
            get {
                return ResourceManager.GetString("WorkTelephone", resourceCulture);
            }
        }
    }
}
